CREATE TABLE TB_GOALKEEPER_PLAYER(
    id UUID NOT NULL UNIQUE,
    name VARCHAR(50) NOT NULL,
    aggression SMALLINT NOT NULL,
    anticipation SMALLINT NOT NULL,
    bravery SMALLINT NOT NULL,
    composure SMALLINT NOT NULL,
    concentration SMALLINT NOT NULL,
    decisions SMALLINT NOT NULL,
    determination SMALLINT NOT NULL,
    flair SMALLINT NOT NULL,
    leadership SMALLINT NOT NULL,
    off_the_ball SMALLINT NOT NULL,
    positioning SMALLINT NOT NULL,
    teamwork SMALLINT NOT NULL,
    vision SMALLINT NOT NULL,
    work_rate SMALLINT NOT NULL,
    acceleration SMALLINT NOT NULL,
    agility SMALLINT NOT NULL,
    balance SMALLINT NOT NULL,
    jumping_reach SMALLINT NOT NULL,
    natural_fitness SMALLINT NOT NULL,
    pace SMALLINT NOT NULL,
    stamina SMALLINT NOT NULL,
    strength SMALLINT NOT NULL,
    free_kick_taking SMALLINT NOT NULL,
    penalty_taking SMALLINT NOT NULL,
    technique SMALLINT NOT NULL,
    first_touch SMALLINT NOT NULL,
    passing SMALLINT NOT NULL,
    aerial_reach SMALLINT NOT NULL,
    command_of_area SMALLINT NOT NULL,
    communication SMALLINT NOT NULL,
    eccentricity SMALLINT NOT NULL,
    handling SMALLINT NOT NULL,
    kicking SMALLINT NOT NULL,
    one_on_ones SMALLINT NOT NULL,
    punching SMALLINT NOT NULL,
    reflexes SMALLINT NOT NULL,
    rushing_out SMALLINT NOT NULL,
    throwing SMALLINT NOT NULL,
    PRIMARY KEY (id)
)