name: fmtools
services:
  traefik:
    image: traefik:v3.3.6
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    depends_on:
      web-app:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - traefik-net
      - web-app-net
      - internal-socket-proxy
      - internal-grafana-net
    volumes:
      - ./traefik/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./traefik/traefik-dynamics.yaml:/etc/config/dynamics.yaml:ro
      - ../../ca/end/server/certs:/etc/certs:ro
      - ../../ca/end/server/private:/etc/keys:ro
      - ../../ca/intermediate/certs/ca-chain.cert.pem:/etc/ca/ca-chain.cert.pem
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik_https.rule=Host(`traefik.docker.localhost`)"
      - "traefik.http.routers.traefik_https.entrypoints=websecure"
      - "traefik.http.routers.traefik_https.service=api@internal"
      - "traefik.http.routers.traefik_https.middlewares=traefik-auth"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=admin:$$2a$$12$$kibrfaSIGAH9XTH/nMWKkOhx59fCoA8rdSjf0hNVdZPGj7GzIygD6"
  
  socket-proxy:
    image: tecnativa/docker-socket-proxy:0.3
    container_name: socket-proxy
    ports:
      - "2375"
    environment:
      - CONTAINERS=1
      - NETWORKS=1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - internal-socket-proxy

networks:
  traefik-net:
  internal-socket-proxy:
    internal: true