package br.com.dgc.fmtools.positions_calculator_service.domain.model.position.defender_centre;

public final class DefenderCentreWeights {
  public static final int CORNERS = 1;
  public static final int CROSSING = 1;
  public static final int DRIBBLING = 1;
  public static final int FINISHING = 1;
  public static final int FIRST_TOUCH = 2;
  public static final int FREE_KICK_TAKING = 1;
  public static final int HEADING = 5;
  public static final int LONG_SHOTS = 1;
  public static final int LONG_THROWS = 1;
  public static final int MARKING = 8;
  public static final int PASSING = 2;
  public static final int PENALTY_TAKING = 1;
  public static final int TACKLING = 5;
  public static final int TECHNIQUE = 1;
  public static final int AGGRESSION = 0;
  public static final int ANTICIPATION = 5;
  public static final int BRAVERY = 2;
  public static final int COMPOSURE = 2;
  public static final int CONCENTRATION = 4;
  public static final int DECISIONS = 10;
  public static final int DETERMINATION = 0;
  public static final int FLAIR = 0;
  public static final int LEADERSHIP = 2;
  public static final int OFF_THE_BALL = 1;
  public static final int POSITIONING = 8;
  public static final int TEAMWORK = 1;
  public static final int VISION = 1;
  public static final int WORK_RATE = 2;
  public static final int ACCELERATION = 6;
  public static final int AGILITY = 6;
  public static final int BALANCE = 2;
  public static final int JUMPING_REACH = 6;
  public static final int NATURAL_FITNESS = 0;
  public static final int PACE = 5;
  public static final int STAMINA = 3;
  public static final int STRENGTH = 6;
}
