package br.com.dgc.fmtools.positions_calculator_service.domain.model.position.wing_back_right_left;

public final class WingBackRightLeftWeights {
  public static final int CORNERS = 1;
  public static final int CROSSING = 3;
  public static final int DRIBBLING = 2;
  public static final int FINISHING = 1;
  public static final int FIRST_TOUCH = 3;
  public static final int FREE_KICK_TAKING = 1;
  public static final int HEADING = 1;
  public static final int LONG_SHOTS = 1;
  public static final int LONG_THROWS = 1;
  public static final int MARKING = 2;
  public static final int PASSING = 3;
  public static final int PENALTY_TAKING = 1;
  public static final int TACKLING = 3;
  public static final int TECHNIQUE = 3;
  public static final int AGGRESSION = 0;
  public static final int ANTICIPATION = 3;
  public static final int BRAVERY = 1;
  public static final int COMPOSURE = 2;
  public static final int CONCENTRATION = 3;
  public static final int DECISIONS = 5;
  public static final int DETERMINATION = 0;
  public static final int FLAIR = 0;
  public static final int LEADERSHIP = 1;
  public static final int OFF_THE_BALL = 2;
  public static final int POSITIONING = 3;
  public static final int TEAMWORK = 2;
  public static final int VISION = 2;
  public static final int WORK_RATE = 2;
  public static final int ACCELERATION = 8;
  public static final int AGILITY = 5;
  public static final int BALANCE = 2;
  public static final int JUMPING_REACH = 1;
  public static final int NATURAL_FITNESS = 0;
  public static final int PACE = 6;
  public static final int STAMINA = 7;
  public static final int STRENGTH = 4;
}
