spring.application.name=formation-calculator-service
server.port=8083
server.shutdown=graceful
management.endpoints.web.exposure.include=*
management.info.git.mode=full

### Database Configuration ###
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:15434/postgres}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

### Rest Client Configuration ###
formation-calculator.positions-calculator-service-url=http://localhost:8082
formation-calculator.squad-manager-service-url=http://localhost:8081
