spring.application.name=formation-calculator-service
server.port=8083
server.shutdown=graceful
spring.main.banner-mode=OFF
management.endpoints.web.exposure.include=*
management.info.git.mode=full
management.metrics.tags.application=${spring.application.name}
management.tracing.sampling.probability=1.0
management.metrics.distribution.percentiles-histogram.http.server.requests=true
logging.pattern.correlation=[application_name=${spring.application.name},trace_id=%X{traceId:-},span_id=%X{spanId:-},trace_flags=%X{traceFlags:-}]

### SSL Configuration ###
server.ssl.enabled=true
server.ssl.bundle=tomcat

spring.ssl.bundle.pem.tomcat.keystore.certificate=/etc/certs/server.cert.pem
spring.ssl.bundle.pem.tomcat.keystore.private-key=/etc/keys/server.key.pem

spring.ssl.bundle.pem.client.truststore.certificate=/certs/ca-chain.cert.pem

### Database Configuration ###
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

### Rest Client Configuration ###
formation-calculator.positions-calculator-service-url=https://positions-calculator-service:8082
formation-calculator.squad-manager-service-url=https://squad-manager-service:8081
