export const VALID_STCL = [
    "STCL,DEEP_LYING_FORWARD,SUPPORT",
    "STCL,DEEP_LYING_FORWARD,ATTACK",
    "STCL,ADVANCED_FORWARD,ATTACK",
    "STCL,TARGET_FORWARD,SUPPORT",
    "STCL,TARGET_FORWARD,ATTACK",
    "STCL,POACHER,ATTACK",
    "STCL,COMPLETE_FORWARD,SUPPORT",
    "STCL,COMPLETE_FORWARD,ATTACK",
    "STCL,PRESSING_FORWARD,DEFEND",
    "STCL,PRESSING_FORWARD,SUPPORT",
    "STCL,PRESSING_FORWARD,ATTACK",
    "STCL,TREQUARTISTA,ATTACK",
    "STCL,FALSE_NINE,SUPPORT"
]

export const VALID_STC = [
    "STC,DEEP_LYING_FORWARD,SUPPORT",
    "STC,DEEP_LYING_FORWARD,ATTACK",
    "STC,ADVANCED_FORWARD,ATTACK",
    "STC,TARGET_FORWARD,SUPPORT",
    "STC,TARGET_FORWARD,ATTACK",
    "STC,POACHER,ATTACK",
    "STC,COMPLETE_FORWARD,SUPPORT",
    "STC,COMPLETE_FORWARD,ATTACK",
    "STC,PRESSING_FORWARD,DEFEND",
    "STC,PRESSING_FORWARD,SUPPORT",
    "STC,PRESSING_FORWARD,ATTACK",
    "STC,TREQUARTISTA,ATTACK",
    "STC,FALSE_NINE,SUPPORT"
]

export const VALID_STCR = [
    "STCR,DEEP_LYING_FORWARD,SUPPORT",
    "STCR,DEEP_LYING_FORWARD,ATTACK",
    "STCR,ADVANCED_FORWARD,ATTACK",
    "STCR,TARGET_FORWARD,SUPPORT",
    "STCR,TARGET_FORWARD,ATTACK",
    "STCR,POACHER,ATTACK",
    "STCR,COMPLETE_FORWARD,SUPPORT",
    "STCR,COMPLETE_FORWARD,ATTACK",
    "STCR,PRESSING_FORWARD,DEFEND",
    "STCR,PRESSING_FORWARD,SUPPORT",
    "STCR,PRESSING_FORWARD,ATTACK",
    "STCR,TREQUARTISTA,ATTACK",
    "STCR,FALSE_NINE,SUPPORT"
]



export const VALID_AML = [
    "AML,WINGER,SUPPORT",
    "AML,WINGER,ATTACK",
    "AML,ADVANCED_PLAYMAKER,SUPPORT",
    "AML,ADVANCED_PLAYMAKER,ATTACK",
    "AML,INSIDE_FORWARD,SUPPORT",
    "AML,INSIDE_FORWARD,ATTACK",
    "AML,TREQUARTISTA,ATTACK",
    "AML,WIDE_TARGET_FORWARD,SUPPORT",
    "AML,WIDE_TARGET_FORWARD,ATTACK",
    "AML,RAUMDEUTER,ATTACK",
    "AML,INVERTED_WINGER,SUPPORT",
    "AML,INVERTED_WINGER,ATTACK",
]

export const VALID_AMCL = [
    "AMCL,ATTACKING_MIDFIELDER,SUPPORT",
    "AMCL,ATTACKING_MIDFIELDER,ATTACK",
    "AMCL,ADVANCED_PLAYMAKER,SUPPORT",
    "AMCL,ADVANCED_PLAYMAKER,ATTACK",
    "AMCL,TREQUARTISTA,ATTACK",
    "AMCL,ENGANCHE,SUPPORT",
    "AMCL,SHADOW_STRIKER,ATTACK",
]

export const VALID_AMC = [
    "AMC,ATTACKING_MIDFIELDER,SUPPORT",
    "AMC,ATTACKING_MIDFIELDER,ATTACK",
    "AMC,ADVANCED_PLAYMAKER,SUPPORT",
    "AMC,ADVANCED_PLAYMAKER,ATTACK",
    "AMC,TREQUARTISTA,ATTACK",
    "AMC,ENGANCHE,SUPPORT",
    "AMC,SHADOW_STRIKER,ATTACK",
]

export const VALID_AMCR = [
    "AMCR,ATTACKING_MIDFIELDER,SUPPORT",
    "AMCR,ATTACKING_MIDFIELDER,ATTACK",
    "AMCR,ADVANCED_PLAYMAKER,SUPPORT",
    "AMCR,ADVANCED_PLAYMAKER,ATTACK",
    "AMCR,TREQUARTISTA,ATTACK",
    "AMCR,ENGANCHE,SUPPORT",
    "AMCR,SHADOW_STRIKER,ATTACK",
]

export const VALID_AMR = [
    "AMR,WINGER,SUPPORT",
    "AMR,WINGER,ATTACK",
    "AMR,ADVANCED_PLAYMAKER,SUPPORT",
    "AMR,ADVANCED_PLAYMAKER,ATTACK",
    "AMR,INSIDE_FORWARD,SUPPORT",
    "AMR,INSIDE_FORWARD,ATTACK",
    "AMR,TREQUARTISTA,ATTACK",
    "AMR,WIDE_TARGET_FORWARD,SUPPORT",
    "AMR,WIDE_TARGET_FORWARD,ATTACK",
    "AMR,RAUMDEUTER,ATTACK",
    "AMR,INVERTED_WINGER,SUPPORT",
    "AMR,INVERTED_WINGER,ATTACK",
]



export const VALID_ML = [
    "ML,WIDE_MIDFIELDER,DEFEND",
    "ML,WIDE_MIDFIELDER,SUPPORT",
    "ML,WIDE_MIDFIELDER,ATTACK",
    "ML,WIDE_MIDFIELDER,AUTOMATIC",
    "ML,WINGER,SUPPORT",
    "ML,WINGER,ATTACK",
    "ML,DEFENSIVE_WINGER,DEFEND",
    "ML,DEFENSIVE_WINGER,SUPPORT",
    "ML,WIDE_PLAYMAKER,SUPPORT",
    "ML,WIDE_PLAYMAKER,ATTACK",
    "ML,INVERTED_WINGER,SUPPORT",
    "ML,INVERTED_WINGER,ATTACK",
]
export const VALID_MCL = [
    "MCL,CENTRAL_MIDFIELDER,DEFEND",
    "MCL,CENTRAL_MIDFIELDER,SUPPORT",
    "MCL,CENTRAL_MIDFIELDER,ATTACK",
    "MCL,CENTRAL_MIDFIELDER,AUTOMATIC",
    "MCL,DEEP_LYING_PLAYMAKER,DEFEND",
    "MCL,DEEP_LYING_PLAYMAKER,SUPPORT",
    "MCL,BOX_TO_BOX_MIDFIELDER,SUPPORT",
    "MCL,ADVANCED_PLAYMAKER,SUPPORT",
    "MCL,ADVANCED_PLAYMAKER,ATTACK",
    "MCL,BALL_WINNING_MIDFIELDER,DEFEND",
    "MCL,BALL_WINNING_MIDFIELDER,SUPPORT",
    "MCL,ROAMING_PLAYMAKER,SUPPORT",
    "MCL,MEZZALA,SUPPORT",
    "MCL,MEZZALA,ATTACK",
    "MCL,CARRILERO,SUPPORT",
]
export const VALID_MC = [
    "MC,CENTRAL_MIDFIELDER,DEFEND",
    "MC,CENTRAL_MIDFIELDER,SUPPORT",
    "MC,CENTRAL_MIDFIELDER,ATTACK",
    "MC,CENTRAL_MIDFIELDER,AUTOMATIC",
    "MC,DEEP_LYING_PLAYMAKER,DEFEND",
    "MC,DEEP_LYING_PLAYMAKER,SUPPORT",
    "MC,BOX_TO_BOX_MIDFIELDER,SUPPORT",
    "MC,ADVANCED_PLAYMAKER,SUPPORT",
    "MC,ADVANCED_PLAYMAKER,ATTACK",
    "MC,BALL_WINNING_MIDFIELDER,DEFEND",
    "MC,BALL_WINNING_MIDFIELDER,SUPPORT",
    "MC,ROAMING_PLAYMAKER,SUPPORT",
]
export const VALID_MCR = [
    "MCR,CENTRAL_MIDFIELDER,DEFEND",
    "MCR,CENTRAL_MIDFIELDER,SUPPORT",
    "MCR,CENTRAL_MIDFIELDER,ATTACK",
    "MCR,CENTRAL_MIDFIELDER,AUTOMATIC",
    "MCR,DEEP_LYING_PLAYMAKER,DEFEND",
    "MCR,DEEP_LYING_PLAYMAKER,SUPPORT",
    "MCR,BOX_TO_BOX_MIDFIELDER,SUPPORT",
    "MCR,ADVANCED_PLAYMAKER,SUPPORT",
    "MCR,ADVANCED_PLAYMAKER,ATTACK",
    "MCR,BALL_WINNING_MIDFIELDER,DEFEND",
    "MCR,BALL_WINNING_MIDFIELDER,SUPPORT",
    "MCR,ROAMING_PLAYMAKER,SUPPORT",
    "MCR,MEZZALA,SUPPORT",
    "MCR,MEZZALA,ATTACK",
    "MCR,CARRILERO,SUPPORT",
]
export const VALID_MR = [
    "MR,WIDE_MIDFIELDER,DEFEND",
    "MR,WIDE_MIDFIELDER,SUPPORT",
    "MR,WIDE_MIDFIELDER,ATTACK",
    "MR,WIDE_MIDFIELDER,AUTOMATIC",
    "MR,WINGER,SUPPORT",
    "MR,WINGER,ATTACK",
    "MR,DEFENSIVE_WINGER,DEFEND",
    "MR,DEFENSIVE_WINGER,SUPPORT",
    "MR,WIDE_PLAYMAKER,SUPPORT",
    "MR,WIDE_PLAYMAKER,ATTACK",
    "MR,INVERTED_WINGER,SUPPORT",
    "MR,INVERTED_WINGER,ATTACK",
]



export const VALID_WBL = [
    "WBL,WING_BACK,DEFEND",
    "WBL,WING_BACK,SUPPORT",
    "WBL,WING_BACK,ATTACK",
    "WBL,WING_BACK,AUTOMATIC",
    "WBL,COMPLETE_WING_BACK,SUPPORT",
    "WBL,COMPLETE_WING_BACK,ATTACK",
    "WBL,INVERTED_WING_BACK,DEFEND",
    "WBL,INVERTED_WING_BACK,SUPPORT",
    "WBL,INVERTED_WING_BACK,ATTACK",
    "WBL,INVERTED_WING_BACK,AUTOMATIC",
]
export const VALID_DMCL = [
    "DMCL,DEFENSIVE_MIDFIELDER,DEFEND",
    "DMCL,DEFENSIVE_MIDFIELDER,SUPPORT",
    "DMCL,DEEP_LYING_PLAYMAKER,DEFEND",
    "DMCL,DEEP_LYING_PLAYMAKER,SUPPORT",
    "DMCL,BALL_WINNING_MIDFIELDER,DEFEND",
    "DMCL,BALL_WINNING_MIDFIELDER,SUPPORT",
    "DMCL,ANCHOR,DEFEND",
    "DMCL,HALF_BACK,DEFEND",
    "DMCL,REGISTA,SUPPORT",
    "DMCL,ROAMING_PLAYMAKER,SUPPORT",
    "DMCL,SEGUNDO_VOLANTE,SUPPORT",
    "DMCL,SEGUNDO_VOLANTE,ATTACK",
]
export const VALID_DM = [
    "DM,DEFENSIVE_MIDFIELDER,DEFEND",
    "DM,DEFENSIVE_MIDFIELDER,SUPPORT",
    "DM,DEEP_LYING_PLAYMAKER,DEFEND",
    "DM,DEEP_LYING_PLAYMAKER,SUPPORT",
    "DM,BALL_WINNING_MIDFIELDER,DEFEND",
    "DM,BALL_WINNING_MIDFIELDER,SUPPORT",
    "DM,ANCHOR,DEFEND",
    "DM,HALF_BACK,DEFEND",
    "DM,REGISTA,SUPPORT",
    "DM,ROAMING_PLAYMAKER,SUPPORT",
]
export const VALID_DMCR = [
    "DMCR,DEFENSIVE_MIDFIELDER,DEFEND",
    "DMCR,DEFENSIVE_MIDFIELDER,SUPPORT",
    "DMCR,DEEP_LYING_PLAYMAKER,DEFEND",
    "DMCR,DEEP_LYING_PLAYMAKER,SUPPORT",
    "DMCR,BALL_WINNING_MIDFIELDER,DEFEND",
    "DMCR,BALL_WINNING_MIDFIELDER,SUPPORT",
    "DMCR,ANCHOR,DEFEND",
    "DMCR,HALF_BACK,DEFEND",
    "DMCR,REGISTA,SUPPORT",
    "DMCR,ROAMING_PLAYMAKER,SUPPORT",
    "DMCR,SEGUNDO_VOLANTE,SUPPORT",
    "DMCR,SEGUNDO_VOLANTE,ATTACK",
]
export const VALID_WBR = [
    "WBR,WING_BACK,DEFEND",
    "WBR,WING_BACK,SUPPORT",
    "WBR,WING_BACK,ATTACK",
    "WBR,WING_BACK,AUTOMATIC",
    "WBR,COMPLETE_WING_BACK,SUPPORT",
    "WBR,COMPLETE_WING_BACK,ATTACK",
    "WBR,INVERTED_WING_BACK,DEFEND",
    "WBR,INVERTED_WING_BACK,SUPPORT",
    "WBR,INVERTED_WING_BACK,ATTACK",
    "WBR,INVERTED_WING_BACK,AUTOMATIC",
]

export const VALID_DL = [
    "DL,FULL_BACK,DEFEND",
    "DL,FULL_BACK,SUPPORT",
    "DL,FULL_BACK,ATTACK",
    "DL,FULL_BACK,AUTOMATIC",
    "DL,WING_BACK,DEFEND",
    "DL,WING_BACK,SUPPORT",
    "DL,WING_BACK,ATTACK",
    "DL,WING_BACK,AUTOMATIC",
    "DL,NO_NONSENSE_FULL_BACK,DEFEND",
    "DL,COMPLETE_WING_BACK,SUPPORT",
    "DL,COMPLETE_WING_BACK,ATTACK",
    "DL,INVERTED_WING_BACK,DEFEND",
    "DL,INVERTED_WING_BACK,SUPPORT",
    "DL,INVERTED_WING_BACK,ATTACK",
    "DL,INVERTED_WING_BACK,AUTOMATIC",
]
export const VALID_DCL = [
    "DCL,CENTRAL_DEFENDER,DEFEND",
    "DCL,CENTRAL_DEFENDER,STOPPER",
    "DCL,CENTRAL_DEFENDER,COVER",
    "DCL,BALL_PLAYING_DEFENDER,DEFEND",
    "DCL,BALL_PLAYING_DEFENDER,STOPPER",
    "DCL,BALL_PLAYING_DEFENDER,COVER",
    "DCL,NO_NONSENSE_CENTRE_BACK,DEFEND",
    "DCL,NO_NONSENSE_CENTRE_BACK,STOPPER",
    "DCL,NO_NONSENSE_CENTRE_BACK,COVER",
    "DCL,WIDE_CENTRE_BACK,DEFEND",
    "DCL,WIDE_CENTRE_BACK,SUPPORT",
    "DCL,WIDE_CENTRE_BACK,ATTACK",
]
export const VALID_DC = [
    "DC,CENTRAL_DEFENDER,DEFEND",
    "DC,CENTRAL_DEFENDER,STOPPER",
    "DC,CENTRAL_DEFENDER,COVER",
    "DC,LIBERO,SUPPORT",
    "DC,LIBERO,ATTACK",
    "DC,BALL_PLAYING_DEFENDER,DEFEND",
    "DC,BALL_PLAYING_DEFENDER,STOPPER",
    "DC,BALL_PLAYING_DEFENDER,COVER",
    "DC,NO_NONSENSE_CENTRE_BACK,DEFEND",
    "DC,NO_NONSENSE_CENTRE_BACK,STOPPER",
    "DC,NO_NONSENSE_CENTRE_BACK,COVER",
    "DC,WIDE_CENTRE_BACK,DEFEND",
    "DC,WIDE_CENTRE_BACK,SUPPORT",
    "DC,WIDE_CENTRE_BACK,ATTACK",
]
export const VALID_DCR = [
    "DCR,CENTRAL_DEFENDER,DEFEND",
    "DCR,CENTRAL_DEFENDER,STOPPER",
    "DCR,CENTRAL_DEFENDER,COVER",
    "DCR,BALL_PLAYING_DEFENDER,DEFEND",
    "DCR,BALL_PLAYING_DEFENDER,STOPPER",
    "DCR,BALL_PLAYING_DEFENDER,COVER",
    "DCR,NO_NONSENSE_CENTRE_BACK,DEFEND",
    "DCR,NO_NONSENSE_CENTRE_BACK,STOPPER",
    "DCR,NO_NONSENSE_CENTRE_BACK,COVER",
    "DCR,WIDE_CENTRE_BACK,DEFEND",
    "DCR,WIDE_CENTRE_BACK,SUPPORT",
    "DCR,WIDE_CENTRE_BACK,ATTACK",
]
export const VALID_DR = [
    "DR,FULL_BACK,DEFEND",
    "DR,FULL_BACK,SUPPORT",
    "DR,FULL_BACK,ATTACK",
    "DR,FULL_BACK,AUTOMATIC",
    "DR,WING_BACK,DEFEND",
    "DR,WING_BACK,SUPPORT",
    "DR,WING_BACK,ATTACK",
    "DR,WING_BACK,AUTOMATIC",
    "DR,NO_NONSENSE_FULL_BACK,DEFEND",
    "DR,COMPLETE_WING_BACK,SUPPORT",
    "DR,COMPLETE_WING_BACK,ATTACK",
    "DR,INVERTED_WING_BACK,DEFEND",
    "DR,INVERTED_WING_BACK,SUPPORT",
    "DR,INVERTED_WING_BACK,ATTACK",
    "DR,INVERTED_WING_BACK,AUTOMATIC",
]

export const VALID_GK = [
    "GK,GOALKEEPER,DEFEND",
    "GK,SWEEPER_KEEPER,DEFEND",
    "GK,SWEEPER_KEEPER,SUPPORT",
    "GK,SWEEPER_KEEPER,ATTACK",
]